apiVersion: apps/v1
kind: Deployment
metadata:
  name: bentley-fastapi
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: bentley-fastapi
  template:
    metadata:
      labels:
        app.kubernetes.io/name: bentley-fastapi
    spec:
      containers:
        - name: fastapi
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
              name: http
