apiVersion: v1
kind: Service
metadata:
  name: bentley-fastapi
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: bentley-fastapi
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
